language:  generic

notifications:
  slack:
    rooms:
      - zeeql:odi4PEJUdmDPkBfjhHIaSdrS

matrix:
    include:
        - os:   osx
          osx_image: xcode11

before_install:
    - ./.travis.d/before-install.sh

install:
    - ./.travis.d/install.sh

script:
    - export PATH="$HOME/usr/bin:$PATH"
    - set -o pipefail
    - xcodebuild -scheme NIOHTTP1-AppKit -configuration Debug   -target NIOHTTP1-AppKit | xcpretty
    - xcodebuild -scheme NIOHTTP1-AppKit -configuration Release -target NIOHTTP1-AppKit | xcpretty
